
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ibrahim
 */
public class splash_screen extends javax.swing.JFrame {

    /**
     * Creates new form splash_screen
     */
    public splash_screen() {
        super("Loading");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loadingBar = new javax.swing.JProgressBar();
        loadingText = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 711));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBar.setBackground(new java.awt.Color(0, 153, 204));
        loadingBar.setForeground(new java.awt.Color(153, 255, 255));
        jPanel2.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1280, 10));

        loadingText.setBackground(new java.awt.Color(0, 153, 204));
        loadingText.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        loadingText.setForeground(new java.awt.Color(255, 255, 255));
        loadingText.setText(" Loading......");
        jPanel2.add(loadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 310, 20));

        loadingValue.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(255, 255, 255));
        loadingValue.setText("0%");
        jPanel2.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 680, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1280, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        splash_screen sp = new splash_screen();
        sp.setVisible(true);
        try {
            for (int i = 0; i <= 100; i++) {

                Thread.sleep(90);
                sp.loadingValue.setText(i + "%");
                sp.loadingBar.setValue(i);
                switch (i) {
                    case 10:
                        sp.loadingText.setText("Welcome To My Project...");
                        break;
                    case 30:
                        sp.loadingText.setText("Loading Modules...");
                        break;
                    case 40:
                        sp.loadingText.setText("E-Library...");
                        break;
                    case 60:
                        sp.loadingText.setText("Turning On Modules...");
                        break;
                    case 70:
                        sp.loadingText.setText("Almost Finished...");
                        break;
                    case 80:
                        sp.loadingText.setText("Connection To Database...");
                        break;
                    case 90:
                        sp.loadingText.setText("Starting....");
                        break;
                    case 100:
                        sp.setVisible(false);
                        login ob = new login();
                        ob.setVisible(true);
                        break;
                    default:
                        break;
                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingText;
    private javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
